spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/picpay
    username: picpay
    password: picpay
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect